const { chromium, expect } = require("@playwright/test");

module.exports = async function testBrowser(base, image) {
  const browser = await chromium.launch();
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
    const errors = [];
    page.on("pageerror", (error) => errors.push(error.message));
    await page.goto(base);
    await page.locator("#email").fill("test@example.com");
    await page.locator("#password").fill("test-password");
    await page.locator('button[type="submit"]').click();
    await expect(page.locator("#apps")).toContainText("Array backup");
    await expect(page.locator(".brand")).toBeVisible();
    await page.locator("#server-add").click({ trial: true });
    page.once("dialog", (dialog) => dialog.accept("Browser Lab"));
    await page.locator("#server-add").click();
    await expect(page.locator("#server-select option:checked")).toHaveText("Browser Lab");
    await expect(page.locator("#empty")).toBeVisible();
    const lab = await page.locator("#server-select").inputValue();
    await page.locator("#add-app-btn").click();
    await expect(page.locator("#app-server")).toHaveValue(lab);
    await expect(page.locator("#image-limits")).toContainText("64 x 64 and 4096 bytes");
    await page.locator("#name").fill("Browser app");
    await page.locator("#url").fill("browser.local");
    await page.locator("#category").fill("browser");
    await page.locator("#image").setInputFiles({ name: "cover.png", mimeType: "image/png", buffer: image });
    await expect(page.locator("#image-preview")).toBeVisible();
    await page.locator("#save-btn").click();
    await expect(page.locator("#form-section")).toBeHidden();
    await expect(page.locator(".app-name")).toHaveText("Browser app");
    await page.locator(".duplicate").click();
    await expect(page.locator("#form-title")).toHaveText("Duplicate app");
    await expect(page.locator("#image-preview")).toBeVisible();
    await page.locator("#name").fill("Browser copy");
    await page.locator("#save-btn").click();
    await expect(page.locator(".app-card")).toHaveCount(2);
    const card = page.locator(".app-card").filter({ has: page.getByRole("heading", { name: "Browser app", exact: true }) });
    await card.locator(".edit").click();
    await page.locator("#remove-preview").click();
    await page.locator("#save-btn").click();
    await expect(card.locator(".app-thumbnail")).toBeHidden();
    await card.locator(".btn-favorite").click();
    await expect(page.locator(".is-favorite")).toHaveCount(1);
    const copy = page.locator(".app-card").filter({ has: page.getByRole("heading", { name: "Browser copy", exact: true }) });
    await expect(copy.locator(".app-thumbnail")).toBeVisible();
    await copy.locator(".btn-favorite").click();
    await expect(page.locator(".is-favorite")).toHaveCount(2);
    const earlier = copy.getByRole("button", { name: "Move favorite earlier: Browser copy", exact: true });
    await earlier.focus();
    await page.keyboard.press("Enter");
    await expect(page.locator(".app-name").first()).toHaveText("Browser copy");
    await expect(page.locator("#toast")).toHaveText("Favorite order saved");
    await copy.dragTo(card);
    await expect(page.locator(".app-name").first()).toHaveText("Browser app");
    await page.locator("#category-filter").selectOption("BROWSER");
    await page.locator("#server-select").selectOption("1");
    await expect(page.locator("#apps")).toContainText("Array backup");
    await expect(page.locator("#apps")).not.toContainText("Browser app");
    await expect(page.locator("#category-filter")).toHaveValue("");
    await page.locator("#search").fill("unrelated search");
    await page.locator("#server-select").selectOption(lab);
    await expect(page.locator("#search")).toHaveValue("");
    await expect(page.locator("#category-filter")).toHaveValue("BROWSER");
    await page.reload();
    await expect(page.locator("#server-select")).toHaveValue(lab);
    await expect(page.locator("#category-filter")).toHaveValue("BROWSER");
    await expect(page.locator(".app-name").first()).toHaveText("Browser app");
    if (process.env.UI_SCREENSHOTS) await page.screenshot({ path: "node_modules/homelinks-desktop.png", fullPage: true, animations: "disabled" });
    await page.setViewportSize({ width: 390, height: 844 });
    await expect(page.locator("#server-select")).toBeVisible();
    await copy.getByRole("button", { name: "Move favorite earlier: Browser copy", exact: true }).click();
    await expect(page.locator(".app-name").first()).toHaveText("Browser copy");
    await page.locator("#view-toggle-btn").click();
    await expect(page.locator(".app-list-item")).toHaveCount(2);
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    if (process.env.UI_SCREENSHOTS) await page.screenshot({ path: "node_modules/homelinks-mobile.png", fullPage: true, animations: "disabled" });
    const lightCanvas = await page.evaluate(() => getComputedStyle(document.body).getPropertyValue("--canvas"));
    await page.emulateMedia({ colorScheme: "dark" });
    expect(await page.evaluate(() => getComputedStyle(document.body).getPropertyValue("--canvas"))).not.toBe(lightCanvas);
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    if (process.env.UI_SCREENSHOTS) await page.screenshot({ path: "node_modules/homelinks-mobile-dark.png", fullPage: true, animations: "disabled" });
    await page.locator(".app-list-item").filter({ has: page.getByRole("heading", { name: "Browser copy", exact: true }) }).locator(".edit").click();
    await page.locator("#app-server").selectOption("1");
    await page.locator("#save-btn").click();
    await expect(page.locator(".app-list-item")).toHaveCount(1);
    await page.locator("#server-select").selectOption("1");
    await expect(page.locator("#apps")).toContainText("Browser copy");
    for (let i = 0; i < 8; i++) {
      const response = await page.request.post(`${base}/api/apps`, { data: { name: `Page ${i}`, url: `http://page${i}.local`, category: "pages", server_id: 1 } });
      expect(response.status()).toBe(201);
    }
    await page.reload();
    await expect(page.locator(".app-list-item:not(.is-favorite)")).toHaveCount(6);
    await page.locator("#next-page").click();
    await expect(page.locator(".app-list-item:not(.is-favorite)")).toHaveCount(3);
    await page.locator("#server-select").selectOption(lab);
    await expect(page.locator("#pagination")).toBeHidden();
    await expect(page.locator("#category-filter")).toHaveValue("BROWSER");
    await page.locator("#server-select").selectOption("1");
    await expect(page.locator("#page-info")).toHaveText("1 of 2");
    await page.locator("#category-filter").selectOption("PAGES");
    await page.locator("#search").fill("Page 7");
    await expect(page.locator(".app-list-item")).toHaveCount(1);
    await expect(page.locator("#apps")).toContainText("Page 7");
    page.once("dialog", (dialog) => dialog.accept());
    await page.locator("#server-delete").click();
    await expect(page.locator("#toast")).toContainText("empty");
    await expect(page.locator("#server-select")).toHaveValue("1");
    expect(errors).toEqual([]);
  } finally {
    await browser.close();
  }
};
